[package]
name = ""
version = "0.0.1"
description = ""
repository = "https://github.com/research-ag/token-handler"
keywords = [ ]
license = "Apache-2.0"

[dependencies]
base = "0.11.2"
icrc84 = "https://github.com/research-ag/icrc-84#main"

[dev-dependencies]
test = "2.0.0"
vector = "0.4.0"

[toolchain]
moc = "0.11.2"
wasmtime = "22.0.0"
