[package]
name = ""
version = "0.0.1"
description = ""
repository = "https://github.com/research-ag/token-handler"
keywords = [ ]
license = "Apache-2.0"

[dependencies]
base = "0.13.5"
icrc84 = "https://github.com/research-ag/icrc-84#main@750573596a0f31780bf0caaab1cd247832a0b0f5"

[dev-dependencies]
test = "2.0.0"
vector = "0.4.1"
await-async = "https://github.com/research-ag/await-async#45092cb97f0b66a513b476e7b586998ac561149c@45092cb97f0b66a513b476e7b586998ac561149c"

[toolchain]
moc = "0.13.5"
wasmtime = "28.0.0"
