[package]
name = "token-handler"
version = "0.0.4"
description = "Complete management of user withdrawals and deposits"
repository = "https://github.com/research-ag/token-handler"
keywords = [ "defi", "icrc-1", "icrc-2", "deposits", "subaccount" ]
license = "Apache-2.0"

[dependencies]
core = "2.0.0"
icrc-84 = "0.1.1"

[dev-dependencies]
async-test = "0.0.2"

[toolchain]
moc = "1.0.0"
