[package]
name = ""
version = "0.0.1"
description = ""
repository = "https://github.com/research-ag/token-handler"
keywords = [ ]
license = "Apache-2.0"

[dependencies]
base = "0.13.0"
icrc84 = "https://github.com/research-ag/icrc-84#main"

[dev-dependencies]
test = "2.0.0"
vector = "0.4.1"
await-async = "https://github.com/research-ag/await-async#dd50b92b7b455c6e3cc5ec136574461539a2d08a"

[toolchain]
moc = "0.13.0"
wasmtime = "22.0.0"
