[package]
name = "token-handler"
version = "0.0.2"
description = "Complete management of user withdrawals and deposits"
repository = "https://github.com/research-ag/token-handler"
keywords = [ "defi", "icrc-1", "icrc-2", "deposits", "subaccount" ]
license = "Apache-2.0"

[dependencies]
base = "0.14.8"
icrc-84 = "0.1.0"

[dev-dependencies]
test = "2.1.1"
vector = "0.4.1"
async-test = "0.0.1"

[toolchain]
moc = "0.14.8"
