[package]
name = ""
version = "0.0.1"
description = ""
repository = "https://github.com/research-ag/token-handler"
keywords = [ ]
license = "Apache-2.0"

[dependencies]
base = "0.11.1"
mrr = "https://github.com/research-ag/motoko-lib#main"

[dev-dependencies]
test = "2.0.0"
