[package]
name = ""
version = "0.0.1"
description = ""
repository = "https://github.com/research-ag/token-handler"
keywords = [ ]
license = "Apache-2.0"

[dependencies]
base = "https://github.com/dfinity/motoko-base"

[dev-dependencies]
test = "2.0.0"
vector = "0.3.1"
await-async = "https://github.com/research-ag/await-async#dd50b92b7b455c6e3cc5ec136574461539a2d08a"

[toolchain]
moc = "0.11.1"
wasmtime = "20.0.2"